adavibeauty/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

# urlpatterns = i18n_patterns(
#     url(r'^$', views.IndexView.as_view()),
#     url(r'^i18n/', include('django.conf.urls.i18n')),
#     url(r'^cart/', include('cart.urls', namespace='cart')),
#     url(r'^checkout/', include('orders.urls', namespace='orders')),
#     url(r'^ckeditor/', include('ckeditor_uploader.urls')),
#     url(r'^contacts/', include('contacts.urls', namespace='contacts')),
#     url(r'^cy/', include('cy.urls', namespace='cy')),
#     url(r'^products/', include('products.urls', namespace='products')),
#     url(r'^blog/', include('bloggiz.urls', namespace='bloggiz')),
#     url(r'^subscribers/', include('subscribers.urls', namespace='subscribers')),
#     url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
#     url(r'^admin/', admin.site.urls),
# )
urlpatterns = [
    url(r'^$', views.IndexView.as_view()),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^checkout/', include('orders.urls', namespace='orders')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
    url(r'^cy/', include('cy.urls', namespace='cy')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^blog/', include('bloggiz.urls', namespace='bloggiz')),
    url(r'^subscribers/', include('subscribers.urls', namespace='subscribers')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import include, url
from cart import views


# app_name = 'cart'
urlpatterns = [
    url('',  include('easycart.urls')),
    url('^$', views.CartDetail.as_view(), name='detail'),
]

cy/urls.py
from django.conf.urls import url
from .views import CyView


app_name = 'currency'
urlpatterns = [
    url(r'^set-currency/$', CyView.as_view(), name='set-currency'),
]

orders/urls.py
from django.conf.urls import url
from . import views


app_name = "orders"
urlpatterns = [
    url('^$', views.CheckoutView.as_view(), name='checkout'),
    url('^created/(?P<pk>[0-9]+)/$', views.CreatedView.as_view(), name='created'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.http import HttpResponseForbidden
from django.urls import reverse
from easycart import BaseItem, BaseCart
from django.views.generic import TemplateView
from django.views.generic.edit import FormMixin
from django.conf import settings
from products.models import Product, ProductVariation
import json
# from .cart import Cart
from .forms import CartAddProductForm
from products.models import Category
from discounts.models import Discount
from discounts.forms import DiscountApplyForm


class Cart(BaseCart):

    def get_queryset(self, pks):
        return ProductVariation.objects.filter(pk__in=pks)


class CartDetail(TemplateView):
    template_name = "cart/detail.html"
    # form_class = DiscountApplyForm

    def get_context_data(self, **kwargs):
        context = super(CartDetail, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.filter(is_active=True)
        # context['discount_apply_form'] = self.get_form()
        return context

    # def post(self, request, *args, **kwargs):
    #     if not request:
    #         return HttpResponseForbidden()
    #     form = self.get_form()
    #
    #     if form.is_valid():
    #         now = timezone.now()
    #         code = form.cleaned_data['discount_code']
    #         try:
    #             discount = Discount.objects.get(discount_code__iexact=code, discount_start_period__gte=now,
    #                                             discount_end_period__lte=now)
    #             request.session['discount_id'] = discount.id
    #         except Discount.DoesNotExist:
    #             request.session['discount_id'] = None
    #         return self.form_valid(form)
    #     else:
    #         return self.form_invalid(form)

    def get_success_url(self):
        return reverse('cart:detail')

cart/templates/cart/detail.html
{% extends 'layout/layout.html' %}
{% load i18n %}
{% get_available_languages as languages %}
{% load staticfiles %}
{% block includefiles %}{% endblock %}
{% block title %}{% trans "Cart" %}{% endblock %}
{% load cy %}
{% block content %}
    <div class="body page height-2" style="min-height:855px">
        <div class="block-left-fon" style="width: calc(390px + 225px); height: 950px"></div>
        <section class="sector blog page">
            <div class="container">
                <div class="title style-4" style="margin-top: 40px;">
                    <h1 class="h2">{% trans "Shopping cart" %}</h1>
                    <div class="clear"></div>
                </div><!-- title -->
                {% if cart.list_items %}
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="woocommerce">
                                <style>
                                    input::-webkit-outer-spin-button,
                                    input::-webkit-inner-spin-button {-webkit-appearance: none;margin: 0;}
                                    input[type='number'] {-moz-appearance: textfield;margin: 0;float: right!important;}
                                    .conteiner-corzin .coupon input.btn {display: block;padding: 17px 20px;font-size: 12px;letter-spacing: 0.2em;border-radius: 50px;border-width: 1px;text-align: center;background-color: #ff887b;height: auto;margin-top: 15px;}
                                    .conteiner-corzin .coupon input.btn:hover {background-color: white;}
                                    .woocommerce .cart-collaterals, .woocommerce-page .cart-collaterals {width: 100%;}
                                </style>
                                <div class="conteiner-corzin">
                                    <div class="wrap">
                                        <div class="item-list cart">
                                            {% for item in cart.list_items %}
                                                <div class="item cart_item">
                                                    <div class="img_link">
                                                        <a href="{% url 'products:detail' item.obj.product.category.id item.obj.product.sub_categories.slug item.obj.product.id %}" class="con">
                                                            <img width="250" height="300" src="{{ item.obj.get_main_image.url }}" class="attachment-shop_thumbnail size-shop_thumbnail wp-post-image" alt="" sizes="(max-width: 250px) 100vw, 250px">
                                                        </a>
                                                    </div>
                                                    <div class="title">
                                                        <a href="{% url 'products:detail' item.obj.product.category.id item.obj.product.sub_categories.slug item.obj.product.id %}" class="name">
                                                            {{ item.obj.product.title }}
                                                        </a>
                                                    </div>
                                                    <div class="articool">
                                                        <span>{% trans "SKU" %}:</span> {{ item.obj.sku }}
                                                    </div>
                                                    <div class="color-type">
                                                        <span class="name">{% trans "Color" %}: </span>
                                                        <div class="cort" style="background-color: {{ item.obj.color_value }}"></div>
                                                    </div>
                                                    <div class="kilkist">
                                                        <div class="input-row">
                                                            <span class="name">{% trans "Quantity" %}: </span>
                                                            <input type="number" onchange="changeQ(this)" step="1" min="1" data-product_id="{{ item.obj.id }}" value="{{ item.quantity }}" class="input-text qty text">
                                                            <span class="less" onclick="decr(this)"></span>
                                                            <span class="more" onclick="incr(this)"></span>
                                                        </div>
                                                    </div>
                                                    <div class="price">
                                                        <span class="price">
                                                            <span class="woocommerce-Price-amount amount">
                                                                <span class="woocommerce-Price-currencySymbol">
                                                                    {{ CURRENCY_ACTIVE.symbol }}
                                                                </span>
                                                                {% change_currency item.price CURRENCY_ACTIVE.abbreviation %}
    {#                                                                            {{ item.price }}#}
                                                            </span>
                                                        </span>
                                                    </div>
                                                    <div class="deleter">
                                                        <button type="button" class="deleter-christ" data-product_id="{{ item.obj.id }}"></button>
                                                    </div>
                                                </div>
                                            {% endfor %}

                                            <div class="last-row-part">
                                                <div class="cart-collaterals">
                                                    <div class="all-price cart_totals">
{#                                                        <div class="cupon actions">#}
{#                                                            <form action="" method="post">#}
{#                                                                {% csrf_token %}#}
{#                                                                <p>{{ discount_apply_form.discount_code.errors }}</p>#}
{#                                                                {{ discount_apply_form }}#}
{#                                                                <button class="btn btn-1" style="margin-top: 10px;" type="submit">#}
{#                                                                    {% trans "Apply coupon" %}#}
{#                                                                </button>#}
{#                                                            </form>#}
{#                                                        </div>#}
                                                        <div class="checkout_wrap">
                                                            <a href="{% url 'orders:checkout' %}" class="btn btn-1 submition-butt checkout-button">
                                                                <span>{% trans "Checkout" %}</span>
                                                            </a>
                                                        </div>
                                                        <div class="allcost" style="text-align: right;">
                                                            <div>
                                                                <span>{% trans "Subtotal before shipping" %}:</span>
                                                                <span>
                                                                    <strong>
                                                                        <span class="woocommerce-Price-currencySymbol"> {{ CURRENCY_ACTIVE.symbol }}</span>
                                                                        <span class="woocommerce-Price-amount amount">
                                                                            {% change_currency cart.total_price CURRENCY_ACTIVE.abbreviation %}
                                                                        </span>
                                                                    </strong>
                                                                </span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- col -->
                    </div><!-- box-blog -->
                {% else %}
                    <p>{% trans "Your cart is empty" %}.</p>
                {% endif %}
            </div>
        </section>
    </div>
{% endblock %}