adavibeauty/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

# urlpatterns = i18n_patterns(
#     url(r'^$', views.IndexView.as_view()),
#     url(r'^i18n/', include('django.conf.urls.i18n')),
#     url(r'^cart/', include('cart.urls', namespace='cart')),
#     url(r'^checkout/', include('orders.urls', namespace='orders')),
#     url(r'^ckeditor/', include('ckeditor_uploader.urls')),
#     url(r'^contacts/', include('contacts.urls', namespace='contacts')),
#     url(r'^cy/', include('cy.urls', namespace='cy')),
#     url(r'^products/', include('products.urls', namespace='products')),
#     url(r'^blog/', include('bloggiz.urls', namespace='bloggiz')),
#     url(r'^subscribers/', include('subscribers.urls', namespace='subscribers')),
#     url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
#     url(r'^admin/', admin.site.urls),
# )
urlpatterns = [
    url(r'^$', views.IndexView.as_view()),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^checkout/', include('orders.urls', namespace='orders')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
    url(r'^cy/', include('cy.urls', namespace='cy')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^blog/', include('bloggiz.urls', namespace='bloggiz')),
    url(r'^subscribers/', include('subscribers.urls', namespace='subscribers')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloggiz/urls.py
from django.conf.urls import url
from . import views


app_name = 'bloggiz'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='list'),
    url(r'(?P<slug>[-\w]+)/$', views.PostView.as_view(), name='detail'),
]

cy/urls.py
from django.conf.urls import url
from .views import CyView


app_name = 'currency'
urlpatterns = [
    url(r'^set-currency/$', CyView.as_view(), name='set-currency'),
]

bloggiz/models.py
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from image_cropping import ImageRatioField


# class Category(models.Model):
#     PUBLISHED = True
#     DRAFT = False
#     CAT_CHOICES = (
#         (PUBLISHED, _('Published')),
#         (DRAFT, _('Draft')),
#     )
#     name = models.CharField(max_length=150, unique=True)
#     is_active = models.CharField(max_length=20, choices=CAT_CHOICES, default=DRAFT)
#     date_added = models.DateTimeField(auto_now_add=True)
#
#     class Meta:
#         ordering = ['name']
#         verbose_name = _('Category')
#         verbose_name_plural = _('Categories')

    # def __str__(self):
    #     return self.name


# class Tag(models.Model):
#     title = models.CharField(max_length=30, unique=True, verbose_name=_('Title'))
#     description = models.CharField(max_length=1000, blank=True, verbose_name=_('Description'))
#     is_active = models.BooleanField(default=False, verbose_name=_('Is active'))
#     date_added = models.DateTimeField(auto_now_add=True, verbose_name=_('Date of creation'))
#
#     class Meta:
#         ordering = ['title']
#         verbose_name = _('Tag')
#         verbose_name_plural = _('Tags')
#
#     def __str__(self):
#         return self.title


def upload_path(instance, filename):
    """
    Path to files
    :param instance:
    :param filename:
    :return:
    """
    return "blog/{0}".format(filename)


class Post(models.Model):
    PUBLISHED = True
    DRAFT = False
    POST_CHOICES = (
        (PUBLISHED, _('Published')),
        (DRAFT, _('Draft')),
    )
    title = models.CharField(max_length=500, unique=True, verbose_name=_('Title'))
    slug = models.SlugField(null=True)
    cover_picture = models.ImageField(blank=True, upload_to=upload_path)
    cropping = ImageRatioField('cover_picture', '300x430', free_crop=True)
    # category = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_published = models.BooleanField(choices=POST_CHOICES, default=DRAFT, verbose_name=_('Is published'))
    pretext = models.TextField(verbose_name=_('Short content'))
    content = models.TextField(verbose_name=_('Content'))
    author = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, verbose_name=_('Author'))
    # tag = models.ManyToManyField(Tag, verbose_name=_('Tag'))
    date_added = models.DateTimeField(auto_now_add=True, verbose_name=_('Date of creation'))

    class Meta:
        ordering = ['-date_added']
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')

    def __str__(self):
        return self.title

    def is_post_published(self):
        return self.is_published

    is_post_published.admin_order_field = 'is_published'
    is_post_published.boolean = True
    is_post_published.short_description = _('Is published?')


class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=_('Author'))
    email = models.EmailField(max_length=254)
    comment = models.TextField(verbose_name=_('Comment'))
    parent = models.ForeignKey('self', null=True, blank=True, verbose_name=_('Parent'))
    user = models.ForeignKey(User, null=True, blank=True, verbose_name=_('User'))
    date_added = models.DateTimeField(auto_now_add=True, verbose_name=_('Date of creation'))

    class Meta:
        ordering = ['date_added']
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')

    def __str__(self):
        return self.name

    def children(self):     # replies
        return Comments.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

bloggiz/forms.py
# from django.forms import ModelForm
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import Comments
from ckeditor.widgets import CKEditorWidget


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['name', 'email', 'comment']
        # user = forms.IntegerField(widget=forms.HiddenInput, required=False)
        # parent = forms.IntegerField(widget=forms.HiddenInput, required=False)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'placeholder': _('Name'),
        })
        self.fields['email'].widget.attrs.update({
            'placeholder': _('Email'),
        })
        self.fields['comment'].widget.attrs.update({
            'placeholder': _('Comment'),
        })
        # self.fields['comment'] = forms.CharField(widget=CKEditorWidget(config_name='comment'))
        # self.fields['user'] = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=None, required=False)
        # self.fields['parent'] = forms.IntegerField(widget=forms.HiddenInput, required=False)

bloggiz/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from django.http import Http404, HttpResponseForbidden
from django.urls import reverse
from django.conf import settings
from django.core import mail

from .models import Post, Comments
from .forms import CommentForm
from products.models import Category
from meta.views import MetadataMixin, Meta
from templated_email import send_templated_mail


class IndexView(ListView):
    model = Post
    template_name = "bloggiz/list.html"
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.filter(is_active=True)
        return context


class PostView(MetadataMixin, DetailView, FormMixin):
    model = Post
    template_name = "bloggiz/detail.html"
    form_class = CommentForm
    use_og = True

    def get(self, request, *args, **kwargs):
        self.title = self.get_post().title
        self.description = self.get_post().content
        self.image = "%s" % self.get_post().cover_picture
        self.url = self.get_success_url()
        self.object_type = 'Article'
        self.custom_namespace = 'blog'
        if request.user.is_authenticated:
            self.initial = {
                'name': request.user.username,
                'email': request.user.email,
            }
        # print(request.META['HTTP_REFERER'])
        return super(PostView, self).get(request, *args, **kwargs)

    def get_post(self):
        if 'slug' in self.kwargs:
            # self.prod_var = Product.objects.filter(pk=self.kwargs['pk'])
            return get_object_or_404(Post, slug=self.kwargs['slug'])
        raise Http404

    def get_context_data(self, **kwargs):
        context = super(PostView, self).get_context_data(**kwargs)
        context['single_post'] = Post.objects.get(slug=self.kwargs['slug'])
        context['comments'] = Comments.objects.filter(post__slug=self.kwargs['slug']).filter(parent=None)
        context['category_list'] = Category.objects.filter(is_active=True)
        context['form'] = self.get_form()
        if self.request.user.is_authenticated:
            context['user'] = User.objects.get(pk=self.request.user.id)
        else:
            context['user'] = None

        return context

    def post(self, request, *args, **kwargs):
        if not request:
            return HttpResponseForbidden
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.post = Post.objects.get(slug=self.kwargs['slug'])
        obj.parent = None
        try:
            parent_id = int(self.request.POST.get('parent'))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comments.objects.filter(pk=parent_id)
            if parent_qs.exists():
                obj.parent = parent_qs.first()
                # link = "http://127.0.0.1:8000" + self.get_success_url() + "#reply" + str(parent_id)
                link = self.request.META['HTTP_REFERER'] + "#reply" + str(parent_id)
                # msg = "This user (%s) replied to your comment. Follow this link: %s" % (obj.name, link)
                # with mail.get_connection() as connection:
                #     mail.EmailMessage(
                #         "Reply to comment", msg, settings.DEFAULT_FROM_EMAIL, [parent_qs.get().email],
                #         connection=connection
                #     ).send()
                send_templated_mail(
                    template_name='comment_reply',
                    from_email='noreply@sandbox8f86f5175eec47f39c7887ee6e45e3a9.mailgun.org',
                    recipient_list=[parent_qs.get().email],
                    context={
                        'full_name': parent_qs.get().name,
                        'user': obj.name,
                        'link': link
                    }
                )

        if self.request.user.is_authenticated:
            obj.user = User.objects.get(pk=self.request.user.id)
        obj.save()
        return super(PostView, self).form_valid(form)

    def get_success_url(self):
        return reverse('bloggiz:detail', kwargs={'slug': self.kwargs['slug']})

bloggiz/templates/bloggiz/detail.html
{% extends 'layout/layout.html' %}
{% load i18n %}
{% get_available_languages as languages %}
{% block title %}{{ single_post.title }}{% endblock %}
{% load staticfiles %}
{% block includefiles %}
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.js' %}"></script>
{% endblock %}
{% load ratings %}
{% load social_share %}
{% block content %}
    <div data-spy="scroll" data-target=".replies" class="body page height-2" style="min-height:855px">
        <div class="block-left-fon" style="width: calc(381.5px + 225px); height: 3041px"></div>
        <section class="sector blog page single">
            <div class="container">
                <div class="title style-4 row">
                    <div class="col-xs-12"></div>
                    <div class="clear"></div>
                </div><!-- title -->
                <div class="row box-blog wauto">
                    <div class="col-xs-12">
                        <div class="cat cat2 name-article-tree"></div>
                        <div class="headrow">
                            <div class="named">
                                <h1>{{ single_post.title }}</h1>
                            </div>
                            <div class="col-md-6 info">
                                <div><span class="data data2">{{ single_post.date_added }}</span></div>
                                <div class="maker">
                                    <span>by</span>
                                    <b>{{ single_post.author }}</b>
                                </div>
                                <div class="typers">
                                    <img src="{% static 'img/typer.png' %}" alt="">
                                    <span>{{ comments|length }}</span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <!-- STAR RATING HERE -->
                                {% ratings object %}
                                <!-- !STAR RATING HERE -->
                            </div>
                        </div>
                        <div class="content2">
                            <div class="ctext">{{ single_post.content|safe }}</div>
                        </div>
                        <div class="conteiner-comments">
                            <div class="share-row" id="supsystic">
                                <div class="comment-part">
                                    <span>{% trans "Comments" %}</span>
                                    <b>{{ comments|length }}</b>
                                </div>
                                <div class="share-part">
                                    <span>{% trans "SHARE" %}:</span>
                                    <div data-animation="no-animation" data-icons-animation="no-animation" data-overlay="" data-change-size="" data-button-size="1" style="font-size: 1em;" class="supsystic-social-sharing supsystic-social-sharing-package-flat supsystic-social-sharing-content supsystic-social-sharing-content-align-left supsystic-social-sharing-init supsystic-social-sharing-loaded">
                                        {% post_to_facebook object_or_url '' %}
                                        {% post_to_twitter "Post: {{single_post.title}}." object_or_url "" %}
                                        {% post_to_gplus object_or_url "" %}
                                    </div>
                                </div>
                            </div>
                            {% if comments %}
                                <ul class="replies">
                                    {% for comment in comments %}
                                        <li class="reply" id="reply{{ comment.id }}">
                                            <div class="comment-info">
                                                <img src="{% static 'img/user.svg' %}" alt="user">
                                                {% if comment.user %}
                                                    <span class="name">{{ comment.user.username }}</span>
                                                    <span class="status">{{ comment.user.groups.get.name }}</span>
                                                {% else %}
                                                    <span class="name">{{ comment.name }}</span>
                                                {% endif %}
                                            </div>
                                            <div class="comment-content">
                                                <blockquote>{{ comment.comment|safe }}</blockquote>
                                            </div>
                                            <div class="bottom-comment-pannel">
                                                <p>{% trans "Comment added" %}: <time>{{ comment.date_added|timesince }}</time></p>
                                                <button class="btn btn-xs" id="comment_reply_{{ comment.id }}">
                                                    <span class="fa fa-reply"> {{ comment.children|length }}</span>
                                                    {% trans "Reply" %}
                                                </button>
                                            </div>
                                            {% if comment.children %}
                                                <ul class="replies">
                                                    {% for child in comment.children %}
                                                        <li class="reply">
                                                            <div class="comment-info">
                                                                <img src="{% static 'img/user.svg' %}" alt="user">
                                                                {% if child.user %}
                                                                    <span class="name">{{ child.user.username }}</span>
                                                                    <span class="status">{{ child.user.groups.get.name }}</span>
                                                                {% else %}
                                                                    <span class="name">{{ child.name }}</span>
                                                                {% endif %}
                                                            </div>
                                                            <div class="comment-content">
                                                                <blockquote>{{ child.comment|safe }}</blockquote>
                                                            </div>
                                                            <div class="bottom-comment-pannel">
                                                                <p>{% trans "Reply added" %}: <time>{{ child.date_added|timesince }}</time></p>
                                                                <button class="btn btn-xs" id="comment_reply_{{ child.id }}">
                                                                    <span class="fa fa-reply"> {{ child.children|length }}</span>
                                                                    {% trans "Reply" %}
                                                                </button>
                                                            </div>
                                                            {% if child.children %}
                                                                <ul class="replies">
                                                                    {% for childd in child.children %}
                                                                        <li class="reply">
                                                                            <div class="comment-info">
                                                                                <img src="{% static 'img/user.svg' %}" alt="user">
                                                                                {% if childd.user %}
                                                                                    <span class="name">{{ childd.user.username }}</span>
                                                                                    <span class="status">{{ childd.user.groups.get.name }}</span>
                                                                                {% else %}
                                                                                    <span class="name">{{ childd.name }}</span>
                                                                                {% endif %}
                                                                            </div>
                                                                            <div class="comment-content"><blockquote>{{ childd.comment|safe }}</blockquote></div>
                                                                            <div class="bottom-comment-pannel">
                                                                                <p>{% trans "Reply added" %}: <time>{{ childd.date_added|timesince }}</time></p>
                                                                            </div>
                                                                        </li>
                                                                    {% endfor %}
                                                                </ul>
                                                            {% endif %}
                                                        </li>
                                                    {% endfor %}
                                                </ul>
                                            {% endif %}
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            <div class="form-part" id="comment_form">
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <div class="row-name">
                                        <div class="name">{% trans "pass your comment" %}</div>
                                        {% if user %}
                                            <div class="hidden">
                                                {{ form.name }}
                                                {{ form.email }}
                                            </div>
                                        {% else %}
                                            <div class="input-convert">
                                                {{ form.name }}
                                            <span class="text-danger small">{{ form.name.errors }}</span>
                                            </div>
                                            <div class="input-convert">
                                                {{ form.email }}
                                            <span class="text-danger small">{{ form.email.errors }}</span>
                                            </div>
                                        {% endif %}
                                    </div>
                                    <div class="contein-text">
                                        {{ form.comment }}
                                        <span class="text-danger small">{{ form.comment.errors }}</span>
                                    </div>
                                    <input type="hidden" id="id_parent" name="parent">
                                    {% for field in form %}
                                        {{ field.errors }}
                                    {% endfor %}
                                    <div class="submition-row">
                                        <button type="submit">
                                            <span>{% trans "Submit" %}</span>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        </div><!-- col -->
                    <div class="col-xs-12 constructor-b"></div><!-- row -->
                </div><!-- col -->
            </div><!-- box-blog -->
        </section>
    </div>
{% endblock %}

bloggiz/templates/bloggiz/list.html
{% extends 'layout/layout.html' %}
{% load i18n %}
{% load cropping %}
{% get_available_languages as languages %}
{% block title %}{% trans "Blog" %}{% endblock %}
{% load staticfiles %}
{% block includefiles %}{% endblock %}
{% block content %}
    <div class="body page">
        <div class="block-left-fon" style="width: calc(381.5px + 225px); height: 100%"></div>
        <section class="sector blog page">
            <div class="container">
                <div class="row">
                    <h1 class="h2 title text-center">{% trans "Blog" %}</h1>
                    <!-- title -->
                </div>
                <div class="row box-blog wauto">
                {% if post_list %}
                    {% for post in post_list %}
                        {% if post.is_published %}
                            <div class="col-md-6 col">
                                <div class="item-blog">
                                    <a href="{% url 'bloggiz:detail' post.slug %}"><img src="{% cropped_thumbnail post "cropping" height=430 %}" alt="{{ post.title }}"></a>
                                    <div class="text">
                                        <span class="pull-right data">{{ post.date_added|date }}</span>
                                        <p class="clear"></p>
                                        <h2 class="title">{{ post.title }}</h2>
                                        {{ post.pretext|safe }}
                                        <a href="{% url 'bloggiz:detail' post.slug %}" class="read-more">{% trans "Read" %}</a>
                                    </div><!-- text -->
                                </div><!-- item-blog -->
                            </div><!-- col -->
                        {% endif %}
                    {% endfor %}
                    <div class="container">
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="?page={{ page_obj.previous_page_number }}">{% trans "previous" %}</a>
                                    {% endif %}
                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}">{% trans "next" %}</a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                    </div>
                {% else %}
                    <p class="text-center">{% trans "No posts found" %}</p>
                {% endif %}
                </div><!-- box-blog -->
            </div>
        </section><!-- section blog -->
    </div>
{% endblock %}