adavibeauty/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

# urlpatterns = i18n_patterns(
#     url(r'^$', views.IndexView.as_view()),
#     url(r'^i18n/', include('django.conf.urls.i18n')),
#     url(r'^cart/', include('cart.urls', namespace='cart')),
#     url(r'^checkout/', include('orders.urls', namespace='orders')),
#     url(r'^ckeditor/', include('ckeditor_uploader.urls')),
#     url(r'^contacts/', include('contacts.urls', namespace='contacts')),
#     url(r'^cy/', include('cy.urls', namespace='cy')),
#     url(r'^products/', include('products.urls', namespace='products')),
#     url(r'^blog/', include('bloggiz.urls', namespace='bloggiz')),
#     url(r'^subscribers/', include('subscribers.urls', namespace='subscribers')),
#     url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
#     url(r'^admin/', admin.site.urls),
# )
urlpatterns = [
    url(r'^$', views.IndexView.as_view()),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^checkout/', include('orders.urls', namespace='orders')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
    url(r'^cy/', include('cy.urls', namespace='cy')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^blog/', include('bloggiz.urls', namespace='bloggiz')),
    url(r'^subscribers/', include('subscribers.urls', namespace='subscribers')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloggiz/urls.py
from django.conf.urls import url
from . import views


app_name = 'bloggiz'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='list'),
    url(r'(?P<slug>[-\w]+)/$', views.PostView.as_view(), name='detail'),
]

cart/urls.py
from django.conf.urls import include, url
from cart import views


# app_name = 'cart'
urlpatterns = [
    url('',  include('easycart.urls')),
    url('^$', views.CartDetail.as_view(), name='detail'),
]

contacts/urls.py
from django.conf.urls import url
from . import views


app_name = 'contacts'
urlpatterns = [
    url(r'^$', views.ReviewCreate.as_view(), name='index'),
]

cy/urls.py
from django.conf.urls import url
from .views import CyView


app_name = 'currency'
urlpatterns = [
    url(r'^set-currency/$', CyView.as_view(), name='set-currency'),
]

templates/index.html
{% extends 'layout/layout.html' %}

{% load i18n %}
{% load cropping %}
{% get_available_languages as languages %}
{% load staticfiles %}
{% block includefiles %}
    <script type="text/javascript" src="{% static 'subscribers/subscribers.js' %}"></script>
    <style type="text/css">
        .box-blog img {max-height: 380px;}
    </style>
{% endblock %}
{% block title %}{% trans "Home" %}{% endblock %}
{% load cy %}
{% block content %}
    <div class="main body js onepage-wrapper" data-spy="scroll" data-target=".pos-sm">
        <section class="header section active" style="height: 950px;" data-index="1">
            <div class="box-header">
                <span class="before-object" style="left: calc(50% + 474px);"></span>
                <span class="after-object" style="border-width:950px 950px"></span>
                <span class="slide-object"></span>
                <div class="header-logo">
                    <img src="{% static 'img/logo-slide.png' %}" alt="logo-slide">
                </div>
                <h1 class="h1">{% trans "Adavi Beauty" %}</h1>
                <h2 class="title">{% trans "Organic & Natural" %}</h2>
            </div><!-- box-header -->
        </section><!-- header -->
        <section class="sector pos-sm section" data-index="2" id="second" style="min-height: 1000px;">
            <div class="line-1"></div>
            <div class="line-2"></div>
            <div class="container flexbox">
                <div class="title style-1">
                    <img src="{% static 'img/fon-logo.png' %}" alt="fon-logo">
                    <h2 class="h2 ttnone">{% trans "The Organic Face" %}</h2>
                </div><!-- title -->
                <div class="content text-center max-w850">
                    <p>Adavi Beauty – is the story with a dream…</p>
                    <p>The dream was born from the desire to be beautiful and to share the beauty with others! And that is the law of organic interaction of the surrounding world, created by the Creator with the help of the humans desires by using hands.</p>
                    <p>The story started with&nbsp;<strong>The Organic Face:</strong></p>
                    <p><strong> 95% Organic 100% Natural </strong></p>
                    <p>this organic makeup was created for women who knows the true value of beauty, who have gone through trials and errors of damaging the face and skin.</p>
                    <p><em>Adavi Beauty is a guide to the beautiful state of mind and body!</em></p>
                    <p> <img class="size-full wp-image-867 aligncenter" src="{% static 'img/flovers.png' %}" alt="flovers" width="728" height="200" sizes="(max-width: 728px) 100vw, 728px"></p>
                </div><!-- content -->
            </div>
        </section><!-- section id="d2" -->
    {% if products %}
        <section class="sector product section" data-index="3" style="min-height: 1000px;">
            <div class="container flexbox">
                <div class="title style-2">
                    <h2 class="h2">{% trans "New products" %}</h2>
                </div><!-- title -->
                <div class="new-product row home">
                    <div class="owl1">
                        <div class="woocommerce columns-4">
                            <ul class="products" style="opacity: 1; display: block;">
                                <div class="owl-wrapper-outer">
                                    <div class="owl-wrapper" style="width: 100%; transition: all 0ms ease; transform: translate3d(0px, 0px, 0px);">
                                        {% for product in products %}
                                            <div class="owl-item">
                                                <li class="col product">
                                                    <a href="{% url 'products:detail' product.category.id product.sub_categories.slug product.id %}" class="item">
                                                        <span class="img"></span>
                                                        <img width="115" height="240" src="{{ product.image.url }}"
                                                             class="size-shop_catalog wp-post-image" alt="{{ product.title }}" title="{{ product.title }}"
                                                             sizes="(max-width: 115px) 100vw, 115px">
                                                    </a>
                                                    <h2 class="title" style="height: 45px;">
                                                        <span>{{ product.title }}</span>
                                                        <span>
                                                            <span class="price">
                                                                <span class="woocommerce-Price-amount amount">
                                                                    <span class="woocommerce-Price-currencySymbol">
                                                                        {{ CURRENCY_ACTIVE.symbol }}
                                                                    </span>
                                                                    {% change_currency product.get_first_child_product.price CURRENCY_ACTIVE.abbreviation %}
                                                                </span>
                                                            </span>
                                                        </span>
                                                    </h2>
                                                </li>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </ul>
                        </div>
                    </div><!-- owl1 -->
                </div><!-- row new-product -->
                <p class="text-center">
                    <a href="{% url 'products:index' %}" class="btn">{% trans "View More" %}</a>
                </p>
            </div>
        </section><!-- section product -->
    {% endif %}
        <section class="sector form section" data-index="4" style="min-height: 1025px;">
            <div class="container flexbox">
                <div class="box-form">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="title">
                                <h2 class="title-1 h1">
                                    <p>{% trans "Subscribe" %}<br>
                                        {% trans "on updates" %}!</p>
                                </h2>
                                <h3 class="title-2">
                                    <p>{% blocktrans %}BE IN THE COURSE OF ALL INTERESTS{% endblocktrans %}</p>
                                </h3>
                            </div>
                            <div class="col-lg-6 col-lg-offset-6 col-md-5 col-md-offset-7">
                                <div class="textwidget">
                                    <div class="widget_wysija_cont shortcode_wysija min-height-form">
                                        <div id="mailerlite-form_1" data-temp-id="58a97cb3d28b7">
                                            <div class="mailerlite-form">
                                                <form action="javascript:void(0)" method="post" class="form max-width280">
                                                    <div class="mailerlite-form-inputs">
                                                        <div class="mailerlite-form-field">
                                                            <input id="subscr_email_field" class="form-control" placeholder="{% trans 'Email' %}" type="email" required="required" name="subscr_email">
                                                        </div>
                                                        <div class="mailerlite-form-field">
                                                            <input id="subscr_name_field" class="form-control" placeholder="{% trans 'Name' %}" type="text" required="required" name="subscr_name">
                                                        </div>
                                                        <div class="mailerlite-subscribe-button-container">
                                                            <button type="button" id="addSubscriber" class="mailerlite-subscribe-submit btn">{% trans "Subscribe" %}</button>
                                                        </div>
                                                    </div>
                                                    <div id="snackbar" class="mailerlite-form-response">
                                                        <h4><p><span style="color: #339966;">{% blocktrans %}Thank you for subscribing. A confirmation letter has been sent to you. Check your email.{% endblocktrans %}</span></p></h4>
                                                    </div>
                                                    <div id="error_snackbar">
                                                        <h4><p><span style="color: #991010;">{% blocktrans %}You passed incorrect email address or this email already exists. Please, check your email address. Or you use incognito profile.{% endblocktrans %}</span></p></h4>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- col -->
                    </div>
                </div>
            </div>
        </section><!-- section -->
    {% if posts %}
        <section class="sector blog section" data-index="5" style="min-height: 1000px;">
            <div class="container flexbox">
                <div class="title style-3">
                    <h2 class="h2">{% trans "Blog" %}</h2>
                </div><!-- title -->
                <div class="row box-blog">
                    {% for post in posts %}
                        <div class="col-xs-12 col-md-6 col col-1">
                            <div class="item-blog">
                                <a href="{% url 'bloggiz:detail' post.slug %}"><img src="{% cropped_thumbnail post "cropping" height=430 %}" alt="{{ post.title }}"></a>
                                <div class="text">
                                    <span class="pull-right data">{{ post.date_added|date }}</span>
                                    <p class="clear"></p>
                                    <h3 class="title">{{ post.title }}</h3>
                                    <p class="min-content"></p>
                                    {{ post.pretext|safe }}
                                    <p></p>
                                    <a href="{% url 'bloggiz:detail' post.slug %}" class="read-more">{% trans "Read" %}</a>
                                </div><!-- text -->
                            </div><!-- item-blog -->
                        </div><!-- col -->
                    {% endfor %}
                </div>
                <p class="text-center"><a href="{% url 'bloggiz:list' %}" class="btn">{% trans "Read more" %}</a></p>
            </div>
        </section><!-- section blog -->
    {% endif %}
    </div><!-- body -->
{% endblock %}