adavibeauty/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

# urlpatterns = i18n_patterns(
#     url(r'^$', views.IndexView.as_view()),
#     url(r'^i18n/', include('django.conf.urls.i18n')),
#     url(r'^cart/', include('cart.urls', namespace='cart')),
#     url(r'^checkout/', include('orders.urls', namespace='orders')),
#     url(r'^ckeditor/', include('ckeditor_uploader.urls')),
#     url(r'^contacts/', include('contacts.urls', namespace='contacts')),
#     url(r'^cy/', include('cy.urls', namespace='cy')),
#     url(r'^products/', include('products.urls', namespace='products')),
#     url(r'^blog/', include('bloggiz.urls', namespace='bloggiz')),
#     url(r'^subscribers/', include('subscribers.urls', namespace='subscribers')),
#     url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
#     url(r'^admin/', admin.site.urls),
# )
urlpatterns = [
    url(r'^$', views.IndexView.as_view()),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^checkout/', include('orders.urls', namespace='orders')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
    url(r'^cy/', include('cy.urls', namespace='cy')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^blog/', include('bloggiz.urls', namespace='bloggiz')),
    url(r'^subscribers/', include('subscribers.urls', namespace='subscribers')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloggiz/urls.py
from django.conf.urls import url
from . import views


app_name = 'bloggiz'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='list'),
    url(r'(?P<slug>[-\w]+)/$', views.PostView.as_view(), name='detail'),
]

cart/urls.py
from django.conf.urls import include, url
from cart import views


# app_name = 'cart'
urlpatterns = [
    url('',  include('easycart.urls')),
    url('^$', views.CartDetail.as_view(), name='detail'),
]

contacts/urls.py
from django.conf.urls import url
from . import views


app_name = 'contacts'
urlpatterns = [
    url(r'^$', views.ReviewCreate.as_view(), name='index'),
]

cy/urls.py
from django.conf.urls import url
from .views import CyView


app_name = 'currency'
urlpatterns = [
    url(r'^set-currency/$', CyView.as_view(), name='set-currency'),
]

products/urls.py
from django.conf.urls import url

from . import views


app_name = 'products'

urlpatterns = [
    url(r'^set/$', views.SetPrice.as_view(), name='set-price'),
    url(r'^reset/$', views.ResetPrice.as_view(), name='reset-price'),
    # ex: /products/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /products/1/
    url(r'^(?P<pk>[0-9]+)/$', views.ProductCategoryView.as_view(), name='products_by_category'),
    # ex: /products/1/qwerty/
    url(r'^(?P<fk>[0-9]+)/(?P<slug>[-\w]+)/$', views.ProductSubCategoryView.as_view(), name='products_by_subcategory'),
    # ex: /products/1/qwerty/1/
    url(r'^(?P<fk>[0-9]+)/(?P<slug>[-\w]+)/(?P<pk>[0-9]+)/$', views.ProductView.as_view(), name='detail'),
]

templates/layout/layout.html
{% load i18n %}
{% load google_analytics %}
{% load meta %}
{% load sekizai_tags meta %}

{% get_available_languages as languages %}

<!DOCTYPE html>
<html lang="en" {% render_block 'html_extra' %}>
<head {% meta_namespaces %}>
    {% include "meta/meta.html" %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | Adavibeauty</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script type="text/javascript" src="{% static 'jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'library.js' %}"></script>
    <script type="text/javascript" src="{% static 'main.js' %}"></script>
    <script type="text/javascript" src="{% static "price.js" %}"></script>

    {% load cy %}

    {% block includefiles %}{% endblock %}

    <style>
        #page-preloader {position: fixed;left: 0;top: 0;right: 0;bottom: 0;background: rgba(255,255,255,1);z-index: 100500;}
        #page-preloader .spinner {position: absolute;left: 0;top: 0;z-index: 999;width: 100%;height: 100%;overflow: visible;background: #fff url('{% static 'img/logo-header.png' %}') no-repeat center center;}
        .fancybox-margin{margin-right:0px;}
    </style>
    <script>
        $(window).on('load', function () {var $preloader = $('#page-preloader'),$spinner = $preloader.find('.spinner');$spinner.delay(50).fadeOut('slow');$preloader.delay(50).fadeOut('slow');});
    </script>
    <script>
        var URLS = {addItem: '{% url "cart:cart-add" %}',removeItem: '{% url "cart:cart-remove" %}',changeQuantity: '{% url "cart:cart-change-quantity" %}',emptyCart: '{% url "cart:cart-empty" %}',};
        var SUBURL = {addSubscriber: '{% url "subscribers:subscriber-add" %}',};
        var PRURL = {setPrice: '{% url "products:set-price" %}',resetPrice: '{% url "products:reset-price" %}',};
        var cart = {
            add: function (pk, quantity) {
                quantity = quantity || 1;return $.post(URLS.addItem, {pk: pk, quantity: quantity}, function (xhr) {$("a.cart span").html("");$("a.cart span").html(xhr['itemCount']);$("div.wm").css({display: 'block'}).show(600);}, 'json');
            },
            removeProd: function (itemPK) {
                return $.post(URLS.removeItem, {pk: itemPK}, function (xhr) {$("a.cart span").html("");$("a.cart span").html(xhr['itemCount']);if (window.location.pathname.match(/\/cart\/$/)) {var bt = $('div.cart_item').find('.deleter button[data-product_id="' + itemPK + '"]'),field = bt.parents('div.cart_item'),totalPrice = $("div.allcost span.woocommerce-Price-amount"),tp = (xhr['totalPrice'] * {{ CURRENCY_ACTIVE.dimension }}).toFixed(1);field.remove();totalPrice.text(tp);}if (xhr['itemCount'] == 0) {var wrapp = $('section.sector'),blockForDelete = wrapp.find('div.row');blockForDelete.remove();}}, 'json');
            },
            changeQuantity: function (pk, quantity) {
                return $.post(URLS.changeQuantity, {pk: pk, quantity: quantity}, function (xhr) {var tp = +xhr['totalPrice'];tp = (tp * {{ CURRENCY_ACTIVE.dimension }}).toFixed(1);$('input[data-product_id="'+pk+'"]').val(quantity);$('.cart_totals .woocommerce-Price-amount').text(tp);$('.checkout-button').removeClass('disabled');}, 'json');
            },
            empty: function () {
                $.post(URLS.emptyCart, 'json');
            }
        };
    </script>

</head>
<body class="viewing-page-1">
    {% google_analytics %}
    <!-- PRELOADER -->
    <div id="page-preloader" style="display: block;">
        <span class="spinner" style="display: block;"></span>
    </div>
    <!-- !PRELOADER -->
    <div style="display:none"></div>
    <div class="menu-scroll">
        <ul>
            <li class="menu-item current-menu-item page-item-56 current_page_item menu-item-688"><a href="/">{% trans "Home" %}</a></li>
            <li class="go menu-item current_page_item menu-item-692"><a href="/#second" data-href="off">{% trans "About us" %}</a></li>
            <li class="menu-item menu-item-835"><a href="{% url 'products:index' %}">{% trans "Products" %}</a></li>
            <li class="menu-item menu-item-733"><a href="{% url 'bloggiz:list' %}">{% trans "Blog" %}</a></li>
            <li class="menu-item menu-item-724"><a href="{% url 'contacts:index' %}">{% trans "Contacts" %}</a></li>
        </ul>
    </div>
    <div class="bar-menu">
        <div class="container">
            <div class="logo">
                <a href="/"><img src="{% static 'img/logo-header.png' %}" alt=""></a>
            </div><!-- logo -->
            <div class="menu">
                <ul class="hidden-md hidden-sm hidden-xs">
                    <li><a href="/">{% trans "Home" %}</a></li>
                    <li class="go current_page_item"><a href="/#second" data-href="off">{% trans "About us" %}</a></li>
                    <li><a href="{% url 'products:index' %}">{% trans "Products" %}</a>
                        <div class="dropdown-content_big">
                            <div class="container">
                                {% for category in category_list %}
                                    <div class="wr">
                                        <h2><a href="{% url "products:products_by_category" category.id %}">{{ category|upper }}</a></h2>
                                        <ul>
                                            {% for subcategory in category.get_subcategories %}
                                                <li class="sub_item">
                                                    <a href="{% url "products:products_by_subcategory" category.id subcategory.slug %}">{{ subcategory|upper }}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                    <li><a href="{% url 'bloggiz:list' %}">{% trans "Blog" %}</a></li>
                    <li><a href="{% url 'contacts:index' %}">{% trans "Contacts" %}</a></li>
                </ul>
                <div class="clear"></div>
            </div><!-- menu -->
            <div class="box-cart">
                <button type="button" id="tcon1" class="tcon tcon1 tcon-menu--xcross hidden-lg pull-right" aria-label="toggle menu">
                    <span class="tcon-menu__lines" aria-hidden="true"></span>
                    <span class="tcon-visuallyhidden">toggle menu</span>
                </button>
                <a data-href="" href="{% url 'cart:detail' %}" id="cart_button" class="cart">
                    <img src="{% static 'img/cart-object.png' %}" alt="cart-object">
                    <span>{{ cart.item_count }}</span>
                </a>
                {% include 'cy/currency_base_template.html' %}
            </div><!-- box-cart -->
            <div class="clear"></div>
        </div>
    </div><!-- bar-menu -->
    {% block content %}{% endblock %}
    <div id="end-section" class="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-3 hidden-xs">
                    <a href=""><img src="{% static 'img/logo-foter.png' %}" alt=""></a>
                </div><!-- col -->
                <div class="col-sm-6 col-xs-12">
                    <p class="text-center copyright">©<span id="copyrightTime"></span> AdaviBeauty.com {% trans "All Rights Reserved" %}</p>
                </div><!-- col -->
                <div class="col-sm-3 col-xs-12">
                    <div class="box-ico">
                        <a href="https://www.instagram.com/adavibeauty/" target="_blank" class="icon-instagram demo-icon"></a>
                        <a href="https://www.facebook.com/adavibeauty/" target="_blank" class="icon-facebook demo-icon"></a>
                        <a href="https://www.youtube.com/channel/UCV0W_NNNpT69EwolYTFKZ6Q" target="_blank" class="icon-youtube demo-icon"></a>
                        <a href="https://plus.google.com/u/0/" target="_blank" class="icon-gplus demo-icon"></a>
                    </div>
                </div><!-- col -->
            </div>
        </div>
    </div><!-- footer -->
</body>
</html>